name: scoreflow
description: "High-performance mobile music notation editor and player."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.12.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Самый стабильный плагин для WebView-бриджей с JS
  flutter_inappwebview: ^6.1.5
  # Локальное файловое хранилище партитур (offline-first)
  path_provider: ^2.1.4
  # Идентификаторы партитур
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Прописываем папку под локальный веб-движок нот (AlphaTab/VexFlow)
  assets:
    - assets/www/
    - assets/www/js/
